name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    if: ${{ !(github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) }}
    env:
      images_dir: /opt/images
      TGT: K2P_DRV
      conf_file: k2p_drv.conf
    steps:
      - uses: actions/checkout@v2
      - name: Prepare environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install libtool-bin gperf python3-docutils autopoint gettext
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch'}}
        with:
          limit-access-to-actor: true
      - name: Prebuild
        run: |
          git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
          mkdir -p ${images_dir}
          cd /opt/rt-n56u/toolchain-mipsel
          sh dl_toolchain.sh
      - name: Customer configurations
        run: |
          cp ${conf_file} /opt/rt-n56u/trunk/configs/templates/${TGT}.config
          # build-in smartdns and v2ray
          cd /opt/rt-n56u/trunk
          if [ ! -d "user/smartdns"]; then mkdir -p "user/smartdns"; fi
          if [ ! -d "user/v2ray"]; then mkdir -p "user/v2ray"; fi
          wget -P user/smartdns/ https://raw.githubusercontent.com/pandaxc12/v2ray-padavan-doh/master/padavan/smartdns/Makefile
          wget https://raw.githubusercontent.com/pandaxc12/v2ray-padavan-doh/master/padavan/user/Makefile -O user/Makefile
          wget -P user/v2ray/ https://raw.githubusercontent.com/pandaxc12/v2ray-padavan-doh/master/padavan/v2ray/Makefile

      - name: Start build
        run: |
          cp mod_params.sh /opt/rt-n56u/trunk
          cp ${conf_file} /opt/rt-n56u/trunk/.config
          cd /opt/rt-n56u/trunk
          sudo ./clear_tree
          fakeroot ./build_firmware_ci $TGT
          sudo mv -f images/*.trx /opt/images/
      - name : Upload packages
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: Padavan-packages
          path: /opt/images
